### ISSUE TITLE
insert into database

### ISSUE THREAD

**Issue by pakuteyeng** [LoranKloeze/WhatsAllApp#10]
how to insert into database mysql or another. from console.log(id) ?

**Comment by LoranKloeze** [comment]
Create an API so you can push the data to it from js.

**Comment by whatsappapi** [comment]
@LoranKloeze 

We cant send data to our server.

Refused to connect to 'https://www.whatsapp.com/' because it violates the following Content Security Policy directive: "connect-src 'self' wss://*.web.whatsapp.com https://*.whatsapp.net https://dyn.web.whatsapp.com https://*.giphy.com https://*.tenor.co blob: https://crashlogs.whatsapp.net/wa_clb_data https://crashlogs.whatsapp.net/wa_fls_upload_check https://www.bingapis.com/api/v6/images/search".

**Comment by LoranKloeze** [comment]
I've created a button so you can download numbers + pictures via a zip file.

**Comment by LoranKloeze** [comment]
The zip-file is as far is it goes at this moment. Implementing a connector to a database is a little out of scope at this moment.

**Comment by MuditMathur96** [comment]
Can anybody tell how to open the extracted csv file ,i mean the csv file only contains the name status and [Object Object].
