### ISSUE TITLE
I cannot see when someone online

### ISSUE THREAD

**Issue by snookers1** [LoranKloeze/WhatsAllApp#111]
Hello all,
I added three number in search list. I can see pictures and status texts, but when they are online nothing happen. Green background or last screen doesn't work. Can you help me please?

Notes :
I have a chat session with them.
Also my whatsapp lang is english.
Chrome: 90.0.4430.85  (64 bit)

**Comment by ThirtySix361** [comment]
after todays whatsapp update, neither 

`Store.Wap.subscribePresence(user)` 

nor 

`Store.Presence.find(user)` 

is working. 

(i figured out that this is only true on non-phone-contacts. means i do only get status of a user if i have this number in my phones-contact-book. but not if i create a user with `Store.UserConstructor`)


server socket response is 200 ("ok") but since today i do not get any online status updates with this.
the `Store.Presence._index[user].isOnline` is still only a placeholder object. 
![img](https://36ip.de/s/RiZ.png)

**Comment by sorosons** [comment]
Still not working no any new idea

**Comment by LoranKloeze** [comment]
Yeah, this is a difficult bug. WhatsApp has made it a lot more difficult if not impossible to fetch the online status.
Any pointers are welcome.

**Comment by LoranKloeze** [comment]
Closing as this is a not-gonna-fix as long as WhatsApp doesn't change their API.
