### ISSUE TITLE
We can !!

### ISSUE THREAD

**Issue by nityoday** [LoranKloeze/WhatsAllApp#56]
We can see online status of any person in this world. Whenever someone comes online, we can see online written . Actually there's an app called Netwa which can do the same thing. It also tracks online even if a random person has hidden his last seen.

**Comment by Frogy76** [comment]
10$ per month for tracking 4 Accounts

**Comment by nityoday** [comment]
No I mean see Instructions, you said we can't !

**Comment by muskw** [comment]
@nityoday It may be technically possible, even here that used to happen several months ago. But Loran hasn't been able to get it to work using the new API - it is not an official documented API anyway, he has done a lot of hard work to study how WhatsApp Web works in order to make this project possible. I think he's not much interested in working on this feature of tracking non-chat numbers. It is understandable given that he must be very busy, and this may take too much of an effort.

@LoranKloeze, any idea why this doesn't work? (I remember it worked many months ago, then WhatsApp made some changes.) Can we have an "Issue" thread where the users who are developers can contribute to bring this feature?

**Comment by nityoday** [comment]
@muskw Ohkay It's alright then . We can also track for free using GB WhatsApp.  I mean now the are many apps using this unofficial api somehow

**Comment by muskw** [comment]
I have not tried GB WhatsApp. Any idea how it handles this thing?
